### PR TITLE
Introduce iconoir-react-native package, unify build script

### LINKED ISSUE #49: [FEAT] React Native (Universal) Support
React native doesn't support normal `svg` elements. Instead they have to be imported from [react-native-svg](react-native-svg) compatibility layer for ios, android and web. SVGR supports it by simply passing the `native` flag.

Happy to contribute if it's something you would like to support ✌️

```
{
  "native": true,
  "typescript": true,
  "expandProps": "end",
}
```

### PR DESCRIPTION
**Pull request by paescuj**
Closes #49 

- [x] Adjust `README.md` for iconoir-react-native
- [x] Adjust or unify `CHANGELOG.md`
- [x] ~Testing - I've no experience in React Native~ Let's just see if it's working

With this changes, the build process can be started as follows (from the root directory):
```bash
npm install
npm run build

# For a specific target
npm run build -- iconoir-react-native
```

Note: Once Node v16 becomes LTS we could use npm "workspaces" by adding the following to the root `package.json`:
```json
  "workspaces": [
    "./packages/*"
  ],
```
This would then dedup the dependencies from both packages and would allow us to run `dist` for both packages simultaneously (again from the root directory):
```bash
npm run dist --workspaces
```

EDIT:
Full instructions:
```bash
# From within the root directory

# Install all deps
npm install
npm install --prefix packages/iconoir-react
npm install --prefix packages/iconoir-react-native

# (Re)generate the icons
npm run build

# Bundle the libraries
npm run dist --prefix packages/iconoir-react
npm run dist --prefix packages/iconoir-react-native

# Publish packages
npm publish packages/iconoir-react
npm publish packages/iconoir-react-native
```

### CODE REVIEW

**Comment by paescuj** [comment]
@PianoManDanDan @lucaburgio What do you think? Btw., the build script is now much cooler (async, os tmp dir, ...) 😄

**Comment by lucaburgio** [comment]
Great job @paescuj! 👏🏽

**Comment by lucaburgio** [comment]
@PianoManDanDan is there anything you would like to add?

**Comment by PianoManDanDan** [comment]
Hi both. Sorry it's taken so long for me to get round to this. Just a couple of things:

- I too have no experience with React Native, so don't really know any of the potential pitfalls when it comes to testing the new package.
- At the moment it looks like the libraries don't get bundled at all. If I run `npm publish --dry-run` in either of the package folders after doing an `npm build`, the only files that would be pushed up to npm are the `LICENSE`, `package.json`, `CHANGELOG.md` and `README.md`. By the looks of things the `tsup` script is missed out. 
- I'm assuming you're ok with this @lucaburgio but this will make some of the package building scripts/npm related stuff be pulled up to the repository root. I had vaguely tried to keep package stuff and iconoir stuff as separate as possible before (which is why I put everything in the `packages` folder), but it just depends how much you care about keeping npm stuff separate from the iconoir stuff.

Apart from that it all looks really good to me. Thanks @paescuj for doing all this!!

**Comment by paescuj** [comment]
@PianoManDanDan
Thanks for your feedback, which I really appreciate!

>     * I too have no experience with React Native, so don't really know any of the potential pitfalls when it comes to testing the new package.

I'd say, let's publish it and see if it's working (users can take on the testing part) 😄

>     * ~At the moment it looks like the libraries don't get bundled at all. If I run `npm publish --dry-run` in either of the package folders after doing an `npm build`, the only files that would be pushed up to npm are the `LICENSE`, `package.json`, `CHANGELOG.md` and `README.md`. By the looks of things the `tsup` script is missed out.~ - Ignore me. I re-read your PR properly and realised you need to still run `npm run dist` from each package folder 🤦 Doing this works fine

I know, it's quite confusing! I've added full instructions to my top comment (https://github.com/lucaburgio/iconoir/pull/50#issue-665659540).

>     * I'm assuming you're ok with this @lucaburgio but this will make some of the package building scripts/npm related stuff be pulled up to the repository root. I had vaguely tried to keep package stuff and iconoir stuff as separate as possible before (which is why I put everything in the `packages` folder), but it just depends how much you care about keeping npm stuff separate from the iconoir stuff.

Hmm, I've been thinking about this as well. But IMO it's the simplest solution and should not interfere with anything, and we could still move this stuff somewhere else later on. Ultimately, I leave up the decision to @lucaburgio.

> Apart from that it all looks really good to me. Thanks @paescuj for doing all this!!

Thank you! 😃

**Comment by lucaburgio** [comment]
@paescuj The testing you're referring to in point n.3 will impact only the react-native side? Are we safe with the rest of the react lib already in use?

**Comment by lucaburgio** [comment]
Thank you @paescuj @PianoManDanDan! Good for me to keep some npm stuff mixed in the repository for now. If we will find an alternative in the future even better.

About the testing, is this related only to the react-native side? Is the rest of the current live react lib safe?

**Comment by paescuj** [comment]
> Thank you @paescuj @PianoManDanDan! Good for me to keep some npm stuff mixed in the repository for now. If we will find an alternative in the future even better.

Perfect!

> About the testing, is this related only to the react-native side? Is the rest of the current live react lib safe?

Yup, that's right! The content of the `iconoir-react` package won't change, it's just the build process which has changed.

**Comment by itseramin** [comment]
I'm kind of a newbie to package management, so I'm unable to install the react-native version of the package manually, even after a number of tries... Is there any estimate when will I able to just use the simple `npm i iconoir-react-native` command to use it?

**Comment by paescuj** [comment]
@itseramin Hi, thanks for your interest! The package `iconoir-react-native` hasn't been published yet.
I'm sure this will be done soon.

**Comment by PianoManDanDan** [comment]
Hi @itseramin. I've just published [iconoir-react-native v1.0.0](https://www.npmjs.com/package/iconoir-react-native) to npm so you should now be able to run `npm i iconoir-react-native` to install it into your project. 

@lucaburgio I've added you as a maintainer. @paescuj I'm happy to add you as a maintainer too, but couldn't find a profile for you on npm. Let me know if you want to be added 😄

**Comment by paescuj** [comment]
@PianoManDanDan Thank you very much! I'd be glad to be added as a maintainer! I've just created an account on npm - username is "paescuj".

**Comment by lucaburgio** [comment]
Great! Thank you Daniel 🙏🏻 @PianoManDanDan

**Pull request merged**
