### PR TITLE
feat(flutter): create package

### PR DESCRIPTION
**Pull request by heavybeard**
This branch is in progress by @Ciock and me, following #172 feature request.

I will delete WIP when it will be possible to make a review of this PR.

### CODE REVIEW

**Review by sammarks — COMMENTED** [review]
Looks good with my limited knowledge of Dart! One question: does this support the automatic publishing that we already have in place for the React packages?

Constraints for proper versioning:

1. The version should always match the `version` field of the main `package.json`
2. If there is a publish process, it should automatically be done using GitHub Actions every time a new release is created inside the repository.

I'm not _as_ familiar with the Dart ecosystem, but if importing packages is done via Git URLs, then I would assume that means there isn't any explicit publishing process other than adding the build artifacts to the repo?

**Comment by heavybeard** [comment]
> I would assume that means there isn't any explicit publishing process other than adding the build artifacts to the repo?

Dart uses [pub.dev](https://pub.dev/), It's like `npm` but for `dart`.

> One question: does this support the automatic publishing that we already have in place for the React packages?

I'll add the necessary job needed to do that.

**Comment by heavybeard** [comment]
@sammarks the PR is ready to be reviewed

- I added the task to build the icons for flutter package
- I added the task into prepublish to update the version of pubspec file programmatically
- I added the step into release workflow to publish into pub.dev registry

Now you can follow these steps:
1. Create the developer profile here → https://pub.dev/
2. Create the verified publisher
3. Follow this mini-guide https://github.com/marketplace/actions/publish-dart-flutter-package#credential
4. Add the secret `PUB_CREDENTIAL_JSON` with the file content from step 3

**Comment by heavybeard** [comment]
@sammarks I pushed two more commits to include svg file's content inside the flutter widget in order to respect the react packages style

For #1 point, i follow the name of the `3D*` icon classes prefixing them with `Svg`

Here is where I prefix with `Svg` the icon name when the icon file starts with a number → https://github.com/lucaburgio/iconoir/blob/735643589ae5362e9a9a2a66989c614c6e08fbcd/bin/build.js#L385-L390

And here is the result → https://github.com/lucaburgio/iconoir/blob/735643589ae5362e9a9a2a66989c614c6e08fbcd/packages/iconoir-flutter/lib/3_d_add_hole.dart#L4

In order to respect the react libraries class names → https://github.com/lucaburgio/iconoir/blob/735643589ae5362e9a9a2a66989c614c6e08fbcd/packages/iconoir-react/src/3DAddHole.tsx#L3

**Comment by lucaburgio** [comment]
@sammarks Invite sent ✅

**Comment by sammarks** [comment]
@lucaburgio can you give me access to edit secrets inside this repo so I can add the pub credentials? It's probably an admin role, so you can downgrade me back to maintainer after I've added the secret if you'd like.

**Review by sammarks — APPROVED** [review]
All looks good; I just need to configure the pub credential and then we should be good to go.

**Comment by sammarks** [comment]
Released! https://pub.dev/packages/iconoir_flutter

**Pull request merged**
