### PR TITLE
add a build step that generates a meta data json file

### PR DESCRIPTION
**Pull request by iamtekeste**
Hi @lucaburgio I have updated the build file to include a step that generates a meta data json file. This file will be used by the Figma plugin I plan to build and any future integrations could also use it. I plan to make a fetch call to this json file from the plugin and use the svg names to build out the a url to the assets, for example like this one `https://raw.githubusercontent.com/lucaburgio/iconoir/master/icons/1st-medal.svg`

### CODE REVIEW

**Comment by lucaburgio** [comment]
Thank you @iamtekeste! 🙏🏻

👋🏻 @paescuj do you think the change here is good to go for the overall build.js file?

**Comment by paescuj** [comment]
Thanks, @iamtekeste & @lucaburgio! I've tweaked it a little bit, but besides of this it's looking good!

**Comment by iamtekeste** [comment]
@paescuj thank you for cleaning it up and merging. @lucaburgio Now I can get started on the plugin!!

**Comment by paescuj** [comment]
Great 😃

**Comment by lucaburgio** [comment]
Thank you guys!

**Pull request merged**
