### PR TITLE
Update iconoir-react/iconoir-react-native packages

### PR DESCRIPTION
**Pull request by paescuj**

### CODE REVIEW

**Comment by paescuj** [comment]
@lucaburgio Thanks for merging this!
I've just published the new version of `iconoir-react-native` on npmjs.com. However I don't have access to the `iconoir-react` package. Would you like to publish it or can you give me access rights? Thanks!

**Comment by lucaburgio** [comment]
@paescuj Invited 👍

**Comment by paescuj** [comment]
@lucaburgio Thanks!

**Comment by paescuj** [comment]
@lucaburgio Hmm, sorry I still don't have enough rights to publish the package...

**Comment by lucaburgio** [comment]
That's strange, I see we all have `write` access, I have no other settings other than 2FA. Maybe @PianoManDanDan?

**Comment by paescuj** [comment]
@lucaburgio I just rechecked it and now it seems to work. I guess npmjs.com just needed some time... Thanks! 👍

**Pull request merged**
