### PR TITLE
Fix qr-code.svg icon

### PR DESCRIPTION
**Pull request by mathix420**
Hey,

First of all, thanks for your fantastic work!
I just wanted to change a little thing in the Qr-code design. To me, some lines seemed too long.
I think these minor changes make the icon more clean and familiar.

I know you don't want icon contributions. But since the changes are so small and that I haven't changed the SVG structure. I thought it would make your life a lot easier to open a PR with the changes.

Of course, feel free to close this PR if you disagree with my design changes/opinions.

Have a nice day!

### CODE REVIEW

**Comment by paescuj** [comment]
Thanks, @mathix420!

@lucaburgio: Here's the difference:
qr-code
qr-code(1)

**Comment by mathix420** [comment]
## Better view

New:
new

Old:
old

**Comment by lucaburgio** [comment]
Thank you @mathix420! In this case, I'll accept the icon contribution as I really like your proposal. Great job!

I don't recall why I moved on with the other proposal. Let me update the Figma source and then I'll merge the pull 🙌 Thank you! 💪🏻

**Comment by mathix420** [comment]
Great! Glad to know you like my contribution!
Have a nice evening 🙂

**Pull request merged**
