### PR TITLE
Request #10: Add snapchat icon

### PR DESCRIPTION
**Pull request by alvatip**
Add some modification ass requested:
    
    - Use of a single path for the shape
    - Use of a 1.5px border
    - Cleaned the SVG code
    
So I think that everything should be fine now, if not let me know ;)

### CODE REVIEW

**Comment by lucaburgio** [comment]
great work!

**Comment by lucaburgio** [comment]
@alvatip just found out that the icon is not using symmetry where necessary (for readability and precision), the path is irregular from side to side.

**Comment by alvatip** [comment]
@lucaburgio sorry, I'm still quite unexperimented.
I made some changes and made a duplication of half of the icon, so both halves of the icon use the same path. Tell me if it's fine now, otherwise, I will modify it. 
Here is the link to the SVG: [https://we.tl/t-28N1WaB9cb](url)

**Review by kosticmimi — COMMENTED** [review]
Tvis is Nice info

**Pull request merged**
